
fastlane_version "2.112.0"

default_platform(:ios)

platform :ios do
	# Webhook URL created in Slack
	before_all do
    	ENV["SLACK_URL"] = "https://hooks.slack.com/services/[webhook-url]" 
  	end

  	desc "Submit to a bew beta build  to apple testflight"
  	lane :beta do
    	build_app(scheme: "PantauBersamaStaging")
    	upload_to_testflight
  	end
end
